execute as @s run function main:role/rolereset
execute at @p run clear @s
execute at @p run item replace entity @s armor.chest with minecraft:leather_chestplate{Unbreakable:1b,HideFlags:4,display:{Name:'[{"text":"","italic":false},{"text":"金皮戰甲","color":"gold"}]',color:16770324},AttributeModifiers:[{Slot:"chest",AttributeName:"minecraft:generic.armor",Name:"generic.armor",Amount:3d,Operation:0,UUID:[I;1653818091,1653818091,1653818091,1653818091]}],Enchantments:[{id:"minecraft:protection",lvl:1s}]} 1
execute at @p run item replace entity @s armor.legs with minecraft:leather_leggings{Unbreakable:1b,HideFlags:4,display:{Name:'[{"text":"","italic":false},{"text":"黑金戰褲","color":"gold"}]',color:0},AttributeModifiers:[{Slot:"chest",AttributeName:"minecraft:generic.armor",Name:"generic.armor",Amount:3d,Operation:0,UUID:[I;1653818239,1653818239,1653818239,1653818239]}],Enchantments:[{id:"minecraft:protection",lvl:1s}]} 1
execute at @p run give @s minecraft:iron_sword{Unbreakable:1b,HideFlags:4,display:{Name:'[{"text":"","italic":false},{"text":"黑旗戰刀","color":"dark_aqua"}]',Lore:['[{"text":"","italic":false},{"text":"部落內代代相傳的寶刀 "}]']},AttributeModifiers:[{Slot:"mainhand",AttributeName:"minecraft:generic.attack_damage",Name:"generic.attack_damage",Amount:7d,Operation:0,UUID:[I;1653817527,1653817527,1653817527,1653817527]},{Slot:"mainhand",AttributeName:"minecraft:generic.attack_speed",Name:"generic.attack_speed",Amount:-2d,Operation:0,UUID:[I;1653817526,1653817526,1653817526,1653817526]}]} 1
execute at @p run give @s minecraft:oak_sapling{Unbreakable:1b,HideFlags:5,display:{Name:'[{"text":"","italic":false},{"text":"起源之苗 (Seedling of origin)","color":"dark_green"}]',Lore:['[{"text":"","italic":false},{"text":"【來源】","color":"dark_green"}]','[{"text":"","italic":false},{"text":"「","color":"white"},{"text":"起源之苗","color":"dark_green"},{"text":"」是一個古老的神器","color":"white"}]','[{"text":"","italic":false},{"text":"據說他的力量源自於自然界的萬物","color":"white"}]','[{"text":"","italic":false},{"text":"可以隨機獲得動物的力量並使用","color":"white"}]','[{"text":"","italic":false},{"text":"這個神器擁有豐富的自然知識和神秘的儀式","color":"white"}]','[{"text":"","italic":false},{"text":"能夠與自然界溝通並維持平衡","color":"white"}]','[{"text":"","italic":false}]','[{"text":"","italic":false},{"text":"【使用說明】","color":"white"}]','[{"text":"","italic":false},{"text":"按下Q隨機施放10秒的犀牛之力、奔狼之速、兔子之躍","color":"white"}]','[{"text":"","italic":false}]','[{"text":"","italic":false},{"text":"犀牛之力：力量I、緩速II","color":"dark_red"}]','[{"text":"","italic":false},{"text":"奔狼之速：加速V、飢餓","color":"dark_purple"}]','[{"text":"","italic":false},{"text":"兔子之躍：跳躍IV","color":"white"}]']},Enchantments:[{id:"minecraft:efficiency",lvl:1s}]}
tag @p add ForestPower
give @s bread 64
execute at @p run scoreboard players set @s role 26
scoreboard players set ForestPower_Time Time 0