execute as @s run function main:role/rolereset
execute at @p run clear @s
execute at @p run item replace entity @s armor.head with wither_skeleton_skull{Unbreakable:1,display:{Name:'[{"text":"","italic":false},{"text":"送葬者的頭顱"}]',Lore:['[{"text":"","italic":false},{"text":"怨氣 IV","color":"white"}]']},AttributeModifiers:[{Slot:"head",AttributeName:"generic.armor",Name:"generic.armor",Amount:6,Operation:0,UUID:[I;1653828208,1653828208,1653828208,1653828208]}]} 1
execute at @p run item replace entity @s armor.chest with netherite_chestplate{Unbreakable:1,display:{Name:'[{"text":"","italic":false},{"text":"死者之軀"}]',Lore:['[{"text":"","italic":false},{"text":"怨氣 IV","color":"white"}]']},AttributeModifiers:[{Slot:"chest",AttributeName:"generic.armor",Name:"generic.armor",Amount:2,Operation:0,UUID:[I;1653828333,1653828333,1653828333,1653828333]}],Enchantments:[{"id":"minecraft:binding_curse","lvl":4}]} 1
execute at @p run item replace entity @s armor.feet with netherite_boots{Unbreakable:1,display:{Name:'[{"text":"","italic":false},{"text":"黃泉之靴"}]',Lore:['[{"text":"","italic":false},{"text":"安魂 II","color":"white"}]']},AttributeModifiers:[{Slot:"feet",AttributeName:"generic.armor",Name:"generic.armor",Amount:2,Operation:0,UUID:[I;1653828417,1653828417,1653828417,1653828417]}],Enchantments:[{"id":"minecraft:binding_curse","lvl":4},{"id":"minecraft:soul_speed","lvl":3}]} 1
execute at @p run give @s netherite_shovel{Unbreakable:1,display:{Name:'[{"text":"","italic":false},{"text":"陪葬者","color":"aqua","italic":true}]',Lore:['[{"text":"","italic":false},{"text":"安魂 III","color":"gray"}]','[{"text":"","italic":false},{"text":"生前使用的鏟子","color":"gray"}]','[{"text":"","italic":false},{"text":"有著安魂的效果","color":"gray"}]']},AttributeModifiers:[{Slot:"mainhand",AttributeName:"generic.attack_damage",Name:"generic.attack_damage",Amount:6,Operation:0,UUID:[I;1653828068,1653828068,1653828068,1653828068]},{Slot:"mainhand",AttributeName:"generic.attack_speed",Name:"generic.attack_speed",Amount:-2.3,Operation:0,UUID:[I;1653828067,1653828067,1653828067,1653828067]},{Slot:"mainhand",AttributeName:"generic.knockback_resistance",Name:"generic.knockback_resistance",Amount:0.3,Operation:0,UUID:[I;1653828066,1653828066,1653828066,1653828066]}],Enchantments:[{"id":"minecraft:loyalty","lvl":3},{"id":"minecraft:smite","lvl":3}]} 1
execute at @p run give @s soul_campfire{Unbreakable:1,display:{Name:'[{"text":"","italic":false},{"text":"a","color":"white","obfuscated":true},{"text":"安魂曲","color":"aqua"},{"text":"a","color":"white","obfuscated":true}]',Lore:['[{"text":"","italic":false},{"text":"將死之人，讓我將你安葬吧。","color":"gray"}]','[{"text":"","italic":false},{"text":"丟棄以給予所有敵人最大生命值33.3%的傷害(冷卻:50秒)","color":"white"}]']},Enchantments:[{"id":"minecraft:soul_speed","lvl":3}]} 1
execute at @p run scoreboard players set @s MAXHP 200
tag @s add gravelord
give @s bread 64
execute at @p run scoreboard players set @s role 3
