execute as @s run function main:role/rolereset
execute at @p run clear @s

execute at @p run item replace entity @s armor.chest with minecraft:chainmail_chestplate{Unbreakable:1b,display:{Name:'[{"text":"","italic":false},{"text":"污穢","color":"dark_purple","bold":true},{"text":"者","color":"dark_purple","bold":true,"obfuscated":true}]',Lore:['[{"text":"","italic":false},{"text":"為","color":"dark_purple","bold":true,"obfuscated":true},{"text":"伊戈","color":"yellow","bold":true},{"text":"隆","color":"yellow","bold":true,"obfuscated":true},{"text":"納克"},{"text":"其中","color":"dark_purple","bold":true,"obfuscated":true},{"text":"一個"},{"text":"\\"","color":"yellow","bold":true},{"text":"蔑","color":"red","bold":true},{"text":"稱","color":"red","bold":true,"obfuscated":true},{"text":"\\"","color":"yellow","bold":true}]']},AttributeModifiers:[{Slot:"chest",AttributeName:"minecraft:generic.armor",Name:"generic.armor",Amount:2d,Operation:0,UUID:[I;1682762347,1682762347,1682762347,1682762347]},{Slot:"chest",AttributeName:"minecraft:generic.armor_toughness",Name:"generic.armor_toughness",Amount:2d,Operation:0,UUID:[I;1682762346,1682762346,1682762346,1682762346]},{Slot:"",AttributeName:"minecraft:generic.knockback_resistance",Name:"generic.knockback_resistance",Amount:0.5d,Operation:0,UUID:[I;1682762345,1682762345,1682762345,1682762345]}],Enchantments:[{id:"minecraft:thorns",lvl:2s},{id:"minecraft:binding_curse",lvl:5s},{id:"minecraft:vanishing_curse",lvl:5s}]} 1
execute at @p run give @s minecraft:echo_shard{Unbreakable:1b,display:{Name:'[{"text":"","italic":false},{"text":"惡行","color":"dark_red","bold":true},{"text":"與","color":"dark_red","bold":true,"obfuscated":true},{"text":"敗德"},{"text":"者","obfuscated":true}]',Lore:['[{"text":"","italic":false},{"text":"為","color":"dark_purple","bold":true,"obfuscated":true},{"text":"伊戈","color":"yellow","bold":true},{"text":"隆","color":"yellow","bold":true,"obfuscated":true},{"text":"納克"},{"text":"其中","color":"dark_purple","bold":true,"obfuscated":true},{"text":"一個"},{"text":"\\"","color":"yellow","bold":true},{"text":"蔑","color":"red","bold":true},{"text":"稱","color":"red","bold":true,"obfuscated":true},{"text":"\\"","color":"yellow","bold":true}]']},AttributeModifiers:[{Slot:"mainhand",AttributeName:"minecraft:generic.attack_damage",Name:"generic.attack_damage",Amount:6d,Operation:0,UUID:[I;1682762507,1682762507,1682762507,1682762507]},{Slot:"mainhand",AttributeName:"minecraft:generic.attack_speed",Name:"generic.attack_speed",Amount:-1.5d,Operation:0,UUID:[I;1682762506,1682762506,1682762506,1682762506]},{Slot:"mainhand",AttributeName:"minecraft:generic.knockback_resistance",Name:"generic.knockback_resistance",Amount:0.2d,Operation:0,UUID:[I;1682762505,1682762505,1682762505,1682762505]}],Enchantments:[{id:"minecraft:sweeping",lvl:3s},{id:"minecraft:smite",lvl:3s},{id:"minecraft:aqua_affinity",lvl:3s},{id:"minecraft:bane_of_arthropods",lvl:3s},{id:"minecraft:vanishing_curse",lvl:5s},{id:"minecraft:vanishing_curse",lvl:5s}]} 1
execute at @p run scoreboard players set @s MAXHP 240
tag @s add Ygolonac
give @s bread 64
execute at @p run scoreboard players set @s role 32
scoreboard players set @a Ygolonac_San 0