execute as @s run function main:role/rolereset
execute at @p run clear @s
execute at @p run item replace entity @s armor.head with minecraft:leather_helmet{Unbreakable:1b,HideFlags:64,display:{Name:'[{"text":"","italic":false},{"text":"無貌之神","color":"dark_purple","bold":true}]',Lore:['[{"text":"","italic":false},{"text":"                        "},{"text":"（Avatar）","color":"gold"}]','[{"text":"","italic":false},{"text":"為奈亞拉托提普其中一個 ","color":"dark_red"},{"text":"\\"分身\\"","color":"gold"}]']},AttributeModifiers:[{Slot:"head",AttributeName:"minecraft:generic.armor",Name:"generic.armor",Amount:2d,Operation:0,UUID:[I;1621077599,1621077599,1621077599,1621077599]}],Enchantments:[{id:"minecraft:blast_protection",lvl:4s}]} 1
execute at @p run item replace entity @s armor.chest with minecraft:leather_chestplate{Unbreakable:1b,HideFlags:64,display:{Name:'[{"text":"","italic":false},{"text":"血舌之神","color":"dark_purple","bold":true}]',Lore:['[{"text":"","italic":false},{"text":"                        "},{"text":"（Avatar）","color":"gold"}]','[{"text":"","italic":false},{"text":"為奈亞拉托提普其中一個 ","color":"dark_red"},{"text":"\\"分身\\"","color":"gold"}]']},AttributeModifiers:[{Slot:"chest",AttributeName:"minecraft:generic.armor",Name:"generic.armor",Amount:2d,Operation:0,UUID:[I;1621077733,1621077733,1621077733,1621077733]}],Enchantments:[{id:"minecraft:fire_protection",lvl:4s}]} 1
execute at @p run item replace entity @s armor.legs with minecraft:leather_leggings{Unbreakable:1b,HideFlags:64,display:{Name:'[{"text":"","italic":false},{"text":"黑法老","color":"dark_purple","bold":true}]',Lore:['[{"text":"","italic":false},{"text":"                        "},{"text":"（Avatar）","color":"gold"}]','[{"text":"","italic":false},{"text":"為奈亞拉托提普其中一個 ","color":"dark_red"},{"text":"\\"分身\\"","color":"gold"}]']},AttributeModifiers:[{Slot:"legs",AttributeName:"minecraft:generic.armor",Name:"generic.armor",Amount:2d,Operation:0,UUID:[I;1621077818,1621077818,1621077818,1621077818]}],Enchantments:[{id:"minecraft:projectile_protection",lvl:4s}]} 1
execute at @p run item replace entity @s armor.feet with minecraft:leather_boots{Unbreakable:1b,HideFlags:64,display:{Name:'[{"text":"","italic":false},{"text":"阿荼","color":"dark_purple","bold":true}]',Lore:['[{"text":"","italic":false},{"text":"                        "},{"text":"（Avatar）","color":"gold"}]','[{"text":"","italic":false},{"text":"為奈亞拉托提普其中一個 ","color":"dark_red"},{"text":"\\"分身\\"","color":"gold"}]']},AttributeModifiers:[{Slot:"feet",AttributeName:"minecraft:generic.armor",Name:"generic.armor",Amount:2d,Operation:0,UUID:[I;1621077938,1621077938,1621077938,1621077938]}],Enchantments:[{id:"minecraft:soul_speed",lvl:2s},{id:"minecraft:depth_strider",lvl:2s}]} 1
execute at @p run give @s minecraft:splash_potion{CustomPotionColor:1842204,display:{Name:'[{"text":"","italic":false},{"text":"伏行之混沌","color":"dark_gray"}]'},CustomPotionEffects:[{Id:1b,Amplifier:4b,Duration:500,ShowParticles:0b,ShowIcon:0b},{Id:8b,Amplifier:15b,Duration:500,ShowParticles:0b,ShowIcon:0b},{Id:28b,Amplifier:4b,Duration:500,ShowParticles:0b,ShowIcon:0b}]}
execute at @p run give @s minecraft:nether_wart{display:{Name:'[{"text":"","italic":false},{"text":"暗夜獵手","color":"dark_purple","bold":true}]',Lore:['[{"text":"","italic":false},{"text":"                        "},{"text":"（Avatar）","color":"gold"}]','[{"text":"","italic":false},{"text":"為奈亞拉托提普其中一個 ","color":"dark_red"},{"text":"\\"分身\\"","color":"gold"}]']},AttributeModifiers:[{Slot:"offhand",AttributeName:"minecraft:generic.max_health",Name:"generic.max_health",Amount:4d,Operation:0,UUID:[I;1621078296,1621078296,1621078296,1621078296]},{Slot:"mainhand",AttributeName:"minecraft:generic.attack_damage",Name:"generic.attack_damage",Amount:4d,Operation:0,UUID:[I;1621078295,1621078295,1621078295,1621078295]},{Slot:"mainhand",AttributeName:"minecraft:generic.attack_speed",Name:"generic.attack_speed",Amount:-2.2d,Operation:0,UUID:[I;1621078294,1621078294,1621078294,1621078294]},{Slot:"offhand",AttributeName:"minecraft:generic.knockback_resistance",Name:"generic.knockback_resistance",Amount:0.2d,Operation:0,UUID:[I;1621078293,1621078293,1621078293,1621078293]}],Enchantments:[{id:"minecraft:smite",lvl:4s},{id:"minecraft:bane_of_arthropods",lvl:4s}]} 1
execute at @p run give @s minecraft:splash_potion{CustomPotionColor:4825719,display:{Name:'[{"text":"","italic":false},{"text":"暗夜咆哮者","color":"gray"}]'},CustomPotionEffects:[{Id:3b,Amplifier:2b,Duration:400,ShowParticles:1b,ShowIcon:1b},{Id:5b,Amplifier:0b,Duration:400,ShowParticles:1b,ShowIcon:1b}]}
give @s bread 64
execute at @p run scoreboard players set @s role 35