function main:role/roleskill/sliverbow
function main:role/roleskill/basilisk
function main:role/roleskill/xuanyuan
function main:role/roleskill/gravelord
function main:role/roleskill/badguy
function main:role/roleskill/turtle
function main:role/roleskill/iron_golem
function main:role/roleskill/pillager
function main:role/roleskill/ravager
function main:role/roleskill/vampire
function main:role/roleskill/teleporter19
function main:role/roleskill/26
function main:role/roleskill/32
function main:role/roleskill/idiot
function main:role/roleskill/invisible
function main:role/roleskill/bleeding