scoreboard objectives add teleporter minecraft.dropped:amethyst_shard
scoreboard objectives add teleporter_time dummy
scoreboard players remove @a[tag=teleporter,scores={CoolDown1=1..}] CoolDown1 1
execute at @a[tag=teleporter,scores={teleporter=1..}] run kill @e[type=item,distance=..4,nbt={Item:{id:"minecraft:amethyst_shard"}}]
execute as @a[tag=teleporter,scores={teleporter=1..}] run give @s minecraft:amethyst_shard{Unbreakable:1b,HideFlags:5,display:{Name:'[{"text":"","italic":false},{"text":"維度之核 (Dimensional Core)","color":"dark_purple"}]',Lore:['[{"text":"","italic":false},{"text":"【起源】","color":"dark_purple"}]','[{"text":"","italic":false},{"text":"據說維度之核是由一個名為「維度之神」的強大存在創造的","color":"gray"}]','[{"text":"","italic":false},{"text":"並賦予了它無比的力量和能力","color":"gray"}]','[{"text":"","italic":false},{"text":"只有極少數人能夠掌握維度之核的力量","color":"gray"}]','[{"text":"","italic":false},{"text":"而那些能夠掌握這種力量的人","color":"gray"}]','[{"text":"","italic":false},{"text":"往往也是在維度之間遊歷的冒險者和探險家","color":"gray"}]','[{"text":"","italic":false}]','[{"text":"","italic":false},{"text":"【使用說明】","color":"dark_red"}]','[{"text":"","italic":false},{"text":"按下Q即可傳送要隨機一人旁邊","color":"dark_red"}]','[{"text":"","italic":false},{"text":"並隱形3秒","color":"dark_red"}]','[{"text":"","italic":false},{"text":"(冷卻結束即可再次施放)","color":"gray"}]']},Enchantments:[{id:"minecraft:efficiency",lvl:1s}]} 1
execute as @a[scores={teleporter=1..,CoolDown1=..0},tag=teleporter,tag=!dead] at @a[scores={teleporter=1..,CoolDown1=..0},tag=teleporter,tag=!dead] run particle minecraft:dragon_breath ~ ~1 ~ 0.1 0.4 0.1 0.001 50
tag @a[scores={teleporter=1..,CoolDown1=..0},tag=teleporter,tag=!dead] add teleporter2
execute as @a[tag=teleporter2] run item replace entity @s armor.chest with air
scoreboard players add @a[tag=teleporter2] teleporter_time 1
execute as @a[tag=teleporter2,scores={teleporter_time=60..}] run item replace entity @s armor.chest with minecraft:leather_chestplate{Unbreakable:1b,HideFlags:68,display:{color:8781962,Name:'[{"text":"","italic":false},{"text":"異次元法袍","color":"dark_purple"}]',Lore:['[{"text":"","italic":false},{"text":"【來源】","color":"dark_red"}]','[{"text":"","italic":false},{"text":"一位神秘的魔法師掌握了一種非常強大的魔法","color":"white"}]','[{"text":"","italic":false},{"text":"製作出了一件被稱為「異次元法袍」的神秘法袍","color":"white"}]','[{"text":"","italic":false},{"text":"它可以讓人在現實世界中小小地加速","color":"white"}]','[{"text":"","italic":false},{"text":"但也需要承受更大的身體負擔和疲勞感","color":"white"}]','[{"text":"","italic":false},{"text":"這使得只有少數人能夠真正地使用它。","color":"white"}]']},AttributeModifiers:[{Slot:"chest",AttributeName:"minecraft:generic.armor",Name:"generic.armor",Amount:4d,Operation:0,UUID:[I;1682704971,1682704971,1682704971,1682704971]},{Slot:"chest",AttributeName:"minecraft:generic.armor_toughness",Name:"generic.armor_toughness",Amount:1d,Operation:0,UUID:[I;1682704970,1682704970,1682704970,1682704970]},{Slot:"chest",AttributeName:"minecraft:generic.movement_speed",Name:"generic.movement_speed",Amount:0.1d,Operation:1,UUID:[I;1682704969,1682704969,1682704969,1682704969]}]} 1
tag @a[tag=teleporter2,tag=teleporter,scores={teleporter_time=60..}] remove teleporter2
scoreboard players set @a[tag=teleporter,scores={teleporter_time=60..}] teleporter_time 0
execute as @a[scores={teleporter=1..,CoolDown1=..0},tag=teleporter,tag=!dead] at @a[scores={teleporter=1..,CoolDown1=..0},tag=teleporter,tag=!dead] run tp @s @a[tag=!dead,tag=!teleporter,sort=random,limit=1,gamemode=adventure]
effect give @a[scores={teleporter=1..,CoolDown1=..0},tag=teleporter,tag=!dead] minecraft:invisibility 3 1 true
scoreboard players set @a[scores={teleporter=1..,CoolDown1=..0},tag=teleporter] CoolDown1 400
scoreboard players set @a[scores={teleporter=1..}] teleporter 0
